FROM node:lts-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY server ./server
COPY src ./src
COPY bin ./bin

RUN mkdir -p /home/vertex

ENV AGENT_PORT=3099
ENV AGENT_WORKING_DIR=/home/vertex
ENV AGENT_TOKEN_FILE=/home/vertex/.vertex-token
ARG AGENT_ALLOWED_ORIGINS=http://localhost:3099
ENV AGENT_ALLOWED_ORIGINS=$AGENT_ALLOWED_ORIGINS

EXPOSE 3099

WORKDIR /home/vertex

CMD ["node", "/app/server/agent.js"]
